### ISSUE TITLE
Fix issues in LovewingTest.cs and change osu.Framework.VisualTests

### ISSUE THREAD

**Issue by apap04** [awau/Lovewing#4]

**Comment by sr229** [comment]
Please provide a detailed description of the issue.

**Comment by sr229** [comment]
We want to fix everything as possible so please try to describe what's wrong and we'll try to fix it

**Comment by apap04** [comment]
we could delete osu.Framework.VisualTests. For some reason LovewingTests.cs can't find osu!framework
![image](https://user-images.githubusercontent.com/17275723/27505630-a1db3bd4-5872-11e7-88e8-d30d71f24df2.png)

**Comment by sr229** [comment]
Did you do ```bash
git submodule init
git summodule update
``` 
?

**Comment by apap04** [comment]
no

**Comment by apap04** [comment]
osu.Framework just doesn't work in Lovewing.Test.cs

**Comment by sr229** [comment]
@apap04 works for me.

I told you to init submodule then pull it using ``git submodule update`` then **restart the solution**

**Comment by apap04** [comment]
did that, nothing worked. I typed the commands before opening the solution.

**Comment by sr229** [comment]
ok i think I found the issue.

Seems the CSPROJ doesn't have the references. gonna fix that right away

**Comment by apap04** [comment]
ok gotchu :b:
